### PR TITLE
Setup project , Project first files.

### PR DESCRIPTION
**Pull request by jchernandez87**
Create an index.html file with a Header.
Create an index.css file with a class and color change for the header.
Create a test.MD file that is ignored.

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: 
## Hi @jchernandez87  :handshake: :handshake: :handshake:  , 

Good job so far!
We are so excited to have you here at Microverse, with your first project here!!! :smile: :smile: 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights :high_brightness: :heavy_check_mark: 
:+1: Github flow was correctly used :heavy_check_mark:
:+1: The task implementation success :heavy_check_mark:

## Required Changes ♻️
- [ ] Pull Request should have a descriptive title telling you what changes are inside. Try something like `Add project initial files`, `Setup the project`, ...
- [ ] Pull Request should have a short summary describing introduced changes in more details.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] You have meaningful commit messages, but note that they need to be capitalized, this means that all of commit messages should have their first letter capitalized in that case it will be looking professional. [this article](https://www.freecodecamp.org/news/writing-good-commit-messages-a-practical-guide/) can help you learn about a professional commit message

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Davidosky007** [comment]
Hi @jchernandez87, 

Good job so far! 💪 
I can see you implemented almost all the required changes pointed out by the previous reviewer, however
There are some issues that you still need to work on to go to the next project but you are almost there!


 ## Required Changes ♻️
* the linters check still has errors, please 🙏 fix it and submit for another review using this same PR. 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Temmarie — APPROVED** [review]
# Status: Approved ✔️ 

## Hi @jchernandez87  , 

#### Congratulations! 🎉  Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

#### Cheers and Happy coding!👏👏👏

#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](<https://microverse.zendesk.com/hc/en-us/articles/1500004088561>) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](<https://airtable.com/shrQAqnBwek5a0O0s>)._

**Comment by jchernandez87** [comment]
All tests passed !!

**Pull request merged**
